export const GATEWAY_NAME = "mcw-curseforge-gateway";
export const GATEWAY_VERSION = "0.2.0";
export const MINECRAFT_GAME_ID = 432;
export const DEFAULT_MINECRAFT_MOD_CLASS_ID = 6;
export const MAX_PAGE_SIZE = 50;
export const MAX_RESULT_INDEX = 10_000;
export const MAX_BATCH_SIZE = 50;
export const DEFAULT_TIMEOUT_MS = 12_000;
export const MOD_LOADER_TYPES = { any: 0, forge: 1, fabric: 4, quilt: 5, neoforge: 6 };
